#!/bin/bash
# This is a simple build script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.
cd /var/lib/openshift/521b4547e0b8cdd448000101/app-root/repo/config/ 
cp ConfigOpenShift.js Config.js

