PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX dc: <http://purl.org/dc/terms/> 
PREFIX foaf: <http://xmlns.com/foaf/0.1/> 
PREFIX sioc: <http://rdfs.org/sioc/ns#> 
PREFIX wiki: <http://purl.org/stuff/wiki#>

WITH <http://hyperdata.it/wiki>
DELETE { <http://hyperdata.it/wiki/PageOne>  ?p ?o }  
WHERE { <http://hyperdata.it/wiki/PageOne>  ?p ?o } 
  ;
WITH <http://hyperdata.it/wiki>
DELETE { <http://hyperdata.it/wiki/PageTwo>  ?p ?o }  
WHERE { <http://hyperdata.it/wiki/PageTwo>  ?p ?o } 

 ;

INSERT DATA { 
	GRAPH <http://hyperdata.it/wiki> { 

<http://hyperdata.it/wiki/PageOne>
	dc:format <http://purl.org/NET/mediatypes/text/markdown> ;
    dc:date "2012-04-02T07:24:53Z" ;
    dc:title """Page One""" ;
    sioc:content 
"""## My first post.

In markdown format.

[I'm an inline-style link](https://www.google.com)

[I'm an inline-style relative link to a page in the store (PageTwo)](PageTwo)
""" ;
    a sioc:Post ;
    a wiki:Page ;
    foaf:maker [
        foaf:nick "danja"
    ] .

<http://hyperdata.it/wiki/PageTwo>
	dc:format <http://purl.org/NET/mediatypes/text/markdown> ;
    dc:date "2012-04-02T07:24:54Z" ;
    dc:title "Page Two!" ;
    sioc:content "My second post." ;
    a sioc:Post ;
    a wiki:Page ;
    foaf:maker [
        foaf:nick "danja"
    ] .
	} 
}
